apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraformdemo
  labels:
    app: terraformdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terraformdemo
  template:
    metadata:
      labels:
        app: terraformdemo
    spec:
      containers:
      - name: terraformdemo
        image: sivaganesh07/agguci:21
        ports:
        - containerPort: 8080