apiVersion: v1
kind: Service
metadata:
  name: terraform_cd
  labels:
    app: terraform_cd
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: terraform_cd